/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f4fd56a3-df5b-433a-8881-03f9f30a9e4e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_p7mAFnnIw",
    "aws_user_pools_web_client_id": "7dk6f5c9pgu33u2s7iqqdde0gk",
    "oauth": {}
};


export default awsmobile;
